spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
    generate-ddl: true

app:
  cors:
    allowed-origins: https://localhost:5173

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day

server:
  port: 8443
  ssl:
    key-alias: server
    key-store: classpath:server.p12
    key-store-password: password
    key-store-type: PKCS12
    key-password: password